### ISSUE TITLE
Standalone: Adding new metadata via file upload duplicates all entries

### ISSUE THREAD

**Issue by nluhmann** [achtman-lab/GrapeTree#76]
[GrapeTree_bug.zip](https://github.com/achtman-lab/GrapeTree/files/2118904/GrapeTree_bug.zip)

What I did:
1) Load GrapeTree as .json file (attached)
2) Load new metadata tsv file (attached), first column is node ID as stated in documentation.

What happend: 
In metadata table, instead of matching the node ID, all entries are duplicated, the new entry showing the added metadata. The node size in the tree does not change though.

**Comment by zheminzhou** [comment]
solved
