### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by bifidoman** [achtman-lab/GrapeTree#84]
Hi

I tried to install with pip
$pip install grapetree
---
Then I get this error:
$grapetree
traceback (most recent call last):
  File "/Users/ils/miniconda3/bin/grapetree", line 6, in <module>
    from grapetree.grapetree import main
  File "/Users/ils/miniconda3/lib/python3.6/site-packages/grapetree/grapetree.py", line 29, in <module>
    from module import app
ModuleNotFoundError: No module named 'module'

This my python version:
python version:
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by emmadoughty** [comment]
I'm having the exact same issue that I can't get around. Do you have any advice to fix it?

**Comment by zheminzhou** [comment]
Sorry, this bug is related to Python version comflicts, and has been fixed in the github version. However a new Pypi pachage has not been built. Please pull down and use the github version for the moment. I will make a new release soon.

**Comment by zheminzhou** [comment]
A new version of 2.2 has just released. It works on python >= 3.5 in our test environment. 
Install via
pip install grapetree
