### ISSUE TITLE
Installation with pip

### ISSUE THREAD

**Issue by emmadoughty** [achtman-lab/GrapeTree#86]
Like a previous user, I'm having issues with a pip install. I see that changes were made in order to fix this but I am still having problems... Attempting installation with pip gives me this below. Any help would be greatly appreciated!

Collecting grapetree
  Downloading https://files.pythonhosted.org/packages/00/61/dfb04d0ac9f34719922d2c1091e0adc519ef32a66b157e75141b168a40ef/grapetree-2.0.tar.gz (5.2MB)
    100% |████████████████████████████████| 5.2MB 2.5MB/s
Collecting ete3 (from grapetree)
  Downloading https://files.pythonhosted.org/packages/21/17/3c49b7fafe10ed63bb7904ebf9764b98db726aa5fd482fb006818854bc04/ete3-3.1.1.tar.gz (10.5MB)
    100% |████████████████████████████████| 10.5MB 1.9MB/s
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from grapetree) (1.16.2)
Requirement already satisfied: Flask in ./anaconda3/lib/python3.7/site-packages (from grapetree) (1.0.2)
Requirement already satisfied: networkx in ./anaconda3/lib/python3.7/site-packages (from grapetree) (2.2)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.7/site-packages (from grapetree) (5.6.1)
Requirement already satisfied: numba in ./anaconda3/lib/python3.7/site-packages (from grapetree) (0.43.1)
Collecting Unidecode (from grapetree)
  Downloading https://files.pythonhosted.org/packages/d0/42/d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode-1.1.1-py2.py3-none-any.whl (238kB)
    100% |████████████████████████████████| 245kB 4.6MB/s
Requirement already satisfied: pandas in ./anaconda3/lib/python3.7/site-packages (from grapetree) (0.24.2)
Requirement already satisfied: requests in ./anaconda3/lib/python3.7/site-packages (from grapetree) (2.21.0)
Requirement already satisfied: Werkzeug>=0.14 in ./anaconda3/lib/python3.7/site-packages (from Flask->grapetree) (0.14.1)
Requirement already satisfied: click>=5.1 in ./anaconda3/lib/python3.7/site-packages (from Flask->grapetree) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in ./anaconda3/lib/python3.7/site-packages (from Flask->grapetree) (1.1.0)
Requirement already satisfied: Jinja2>=2.10 in ./anaconda3/lib/python3.7/site-packages (from Flask->grapetree) (2.10)
Requirement already satisfied: decorator>=4.3.0 in ./anaconda3/lib/python3.7/site-packages (from networkx->grapetree) (4.4.0)
Requirement already satisfied: llvmlite>=0.28.0dev0 in ./anaconda3/lib/python3.7/site-packages (from numba->grapetree) (0.28.0)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.7/site-packages (from pandas->grapetree) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.7/site-packages (from pandas->grapetree) (2.8.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.7/site-packages (from requests->grapetree) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./anaconda3/lib/python3.7/site-packages (from requests->grapetree) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.7/site-packages (from requests->grapetree) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from requests->grapetree) (2.8)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.7/site-packages (from Jinja2>=2.10->Flask->grapetree) (1.1.1)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas->grapetree) (1.12.0)
Building wheels for collected packages: grapetree, ete3
  Building wheel for grapetree (setup.py) ... done
  Stored in directory: /Users/doughtye/Library/Caches/pip/wheels/f2/cf/fc/d161248dd7d0dde78e24a3dd1b057a49ed6526dde5321a0d98
  Building wheel for ete3 (setup.py) ... done
  Stored in directory: /Users/doughtye/Library/Caches/pip/wheels/14/90/50/5c10d965e7fb68343d9c5349cce2787ff3e38397946468d640
Successfully built grapetree ete3
Installing collected packages: ete3, Unidecode, grapetree
Successfully installed Unidecode-1.1.1 ete3-3.1.1 grapetree-2.0

Traceback (most recent call last):
  File "/Users/doughtye/anaconda3/bin/grapetree", line 6, in <module>
    from grapetree.grapetree import main
  File "/Users/doughtye/anaconda3/lib/python3.7/site-packages/grapetree/grapetree.py", line 29, in <module>
    from module import app
ModuleNotFoundError: No module named 'module'

**Comment by zheminzhou** [comment]
Sorry, this bug is related to Python version comflicts, and has been fixed in the github version. However a new Pypi pachage has not been built. Please pull down and use the github version for the moment. I will make a new release soon.

**Comment by zheminzhou** [comment]
A new version of 2.2 has just released. It works on python >= 3.5 in our test environment. 
Install via
pip install grapetree
