### ISSUE TITLE
Understanding the grapetree distance computation

### ISSUE THREAD

**Issue by crarlus** [achtman-lab/GrapeTree#87]
Hi,
I have some doubts whether I understand the "--missing" option in the CLI grapetree version correctly. This is what it says in the help file:

```
  --missing HANDLER, -y HANDLER
                        ONLY FOR symmetric DISTANCE MATRIX.
                        0: [DEFAULT] ignore missing data in pairwise comparison.
                        1: Remove column with missing data.
                        2: treat data as an allele.
                        3: Absolute number of allelic differences.
```

I ran the distance calculation for some allele profiles, and when I check the resulting distances and compare it to a custom distance script, I think that `--missing 3` gives me actually something like "ignore missing data in pairwise comparison". 

Could you please clarify:
* What do you mean by "Absolute number of allelic differences"? In earlier versions this case was termed "Naive counting of absolute differences between profiles"? 
* How are "-" entries  treated in this case (`--missing 3`)? 
* And how are the differences computed for `--missing 0`

Also I noticed that the resulting minimum spanning trees MSTreev2 contain the distances according to `--missing 3`? 

Thanks for your help?

**Comment by zheminzhou** [comment]
For --missing 0, the differences are calculated as:
(Number of different alleles)/(Number of loci that present in both genomes)*(Total number of loci)

For --missing 3, missing loci are ignored and only the real different alleles are counted. 
A: 111
B: 12-
Will have a distance of 1. 

"Also I noticed that the resulting minimum spanning trees MSTreev2 contain the distances according to --missing 3?“

Yes, for easy interpretation of the results, the branch lengths of the MSTreeV2 result is re-calculated using "--missing 3".
