### ISSUE TITLE
GrapeTree links via GitHub are not working

### ISSUE THREAD

**Issue by Fiona-McDougall** [achtman-lab/GrapeTree#95]
GrapeTree links via GitHub are not working - I have attempted to view the GrapeTree in Zhou et al, 2018 (GrapeTree: visualization of core genomic relationships among 100,000 bacterial pathogens) - link below, but the tree won't load.
The GrapeTree page opens, but just the "Load Files" icon is active (and no tree appears) - see attached image.

https://achtman-lab.github.io/GrapeTree/MSTree_holder.html?tree=https://raw.githubusercontent.com/achtman-lab/GrapeTree/master/examples/Fig1D-7geneNJ.json

I have also tried my links and the example link in the EnteroBase GrapeTree tutorial, and none are working.

https://achtman-lab.github.io/GrapeTree/MSTree_holder.html?tree=https://raw.githubusercontent.com/achtman-lab/EnteroMSTree/master/examples/ebola.date.json

or the shortened URL. http://bit.ly/2H8py8F

This problem started a few days ago, and I have attempted to use the links on both a Mac and a PC, and using 4 different internet browsers, but none are loading the trees.

![GrapeTree link not working 120221](https://user-images.githubusercontent.com/71738414/107727232-ef974400-6d3e-11eb-8365-b01d16e83b0c.jpg)

**Comment by zheminzhou** [comment]
Many thanks to the report. The old proxy for network based files is not functional anymore. I have updated the codes to use a different site. Both links are now working again.

**Comment by crarlus** [comment]
Hi @zheminzhou The same problems seems to be happening again. Is a fix possible?

Thank you for this great tool!
